import 'package:flutter_online_store/pages/products_page/products.dart';

class MyProducts {
  static List<Product> allProduct = [
    Product(
      id: 1,
      name: 'Chicken Bririyani',
      catagory: 'biriyani',
      image: 'assets/pngtree-chicken-biryani-front-view-png-image_9167532.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 80,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Beef Burger',
      catagory: 'Burger',
      image: 'assets/download (3).jpeg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Chicken Burger',
      catagory: 'SoftDrink',
      image:
          'assets/png-transparent-delicious-beef-burger-delicious-beef-burger-tomato-bread-thumbnail.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Veg Bririyani',
      catagory: 'biriyani',
      image: 'assets/images (2).jpeg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 60,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'HydhraBathi Chicken Bririyani',
      catagory: 'biriyani',
      image: 'assets/pngtree-chicken-biryani-front-view-png-image_9167532.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 140,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Kozhikode Chicken Bririyani',
      catagory: 'biriyani',
      image: 'assets/pngtree-chicken-biryani-front-view-png-image_9167532.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Thalashery Chicken Bririyani',
      catagory: 'biriyani',
      image: 'assets/pngtree-chicken-biryani-front-view-png-image_9167532.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Royal Chicken Bririyani',
      catagory: 'biriyani',
      image: 'assets/pngtree-chicken-biryani-front-view-png-image_9167532.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 220,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Pepsi',
      catagory: 'SoftDrink',
      image: 'assets/images.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'CocaCola',
      catagory: 'SoftDrink',
      image: 'assets/71YBmiSj-cL.jpg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Sprite',
      catagory: 'SoftDrink',
      image: 'assets/download.jpeg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Sting',
      catagory: 'SoftDrink',
      image: 'assets/61d7eK6ueaL.jpg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Sting',
      catagory: 'SoftDrink',
      image: 'assets/61d7eK6ueaL.jpg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 140,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Sting',
      catagory: 'SoftDrink',
      image: 'assets/61d7eK6ueaL.jpg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 20,
      quantity: 1,
    ),
  ];
  static List<Product> burger = [
    Product(
      id: 1,
      name: 'Beef Burger',
      catagory: 'Burger',
      image: 'assets/download (3).jpeg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Chicken Burger',
      catagory: 'SoftDrink',
      image:
          'assets/png-transparent-delicious-beef-burger-delicious-beef-burger-tomato-bread-thumbnail.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Beef Burger',
      catagory: 'Burger',
      image: 'assets/download (3).jpeg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 20,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Chicken Burger',
      catagory: 'SoftDrink',
      image:
          'assets/png-transparent-delicious-beef-burger-delicious-beef-burger-tomato-bread-thumbnail.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 120,
      quantity: 1,
    ),
  ];
  static List<Product> biriyani = [
    Product(
      id: 1,
      name: 'Veg Bririyani',
      catagory: 'biriyani',
      image: 'assets/images (2).jpeg',
      description: 'best chicken Biriyani you have ever tasted',
      price: 60,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'HydhraBathi Chicken Bririyani',
      catagory: 'biriyani',
      image: 'assets/pngtree-chicken-biryani-front-view-png-image_9167532.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 140,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Kozhikode Chicken Bririyani',
      catagory: 'biriyani',
      image: 'assets/pngtree-chicken-biryani-front-view-png-image_9167532.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Thalashery Chicken Bririyani',
      catagory: 'biriyani',
      image: 'assets/pngtree-chicken-biryani-front-view-png-image_9167532.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 120,
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Royal Chicken Bririyani',
      catagory: 'biriyani',
      image: 'assets/pngtree-chicken-biryani-front-view-png-image_9167532.png',
      description: 'best chicken Biriyani you have ever tasted',
      price: 220,
      quantity: 1,
    ),
  ];
}
